export const LOGIN = "LOGIN";
export const FETCHPROFILEBUYER = "FETCH_PROFILE_BUYER";
export const UPDATEPROFILEBUYER = "UPDATE_PROFILE_BUYER";
export const CREATEPROFILE = "CREATE_PROFILE_BUYER";
export const UPDATEIMAGE = "UPDATE_IMAGE";
export const LOADING ="LOADING"
export const FETCHRESTURANTIMAGE ="FETCH_REST_IMAGES"
export const LOGERROR ="LOGERROR"
export const RESOLVEERROR ="RESOLVEERROR"

