export const LOGIN = "LOGIN";
export const FETCHPROFILEBUYER = "FETCH_PROFILE_BUYER";
export const UPDATEPROFILEBUYER = "UPDATE_PROFILE_BUYER";
export const CREATEPROFILE = "CREATE_PROFILE_BUYER";
export const UPDATEIMAGE = "UPDATE_IMAGE";
export const LOADING ="LOADING"
export const FETCHRESTURANTIMAGE ="FETCH_REST_IMAGES"
export const LOGERROR ="LOG_ERROR"
export const FETCHORDERS ="FETCH_ORDERS"
export const RESOLVEERROR ="RESOLVE_ERROR"
export const FETCHSECTION ="FETCH_SECTION"
export const ADDSECTION ="ADD_SECTION"
export const FETCHITEMS ="FETCH_ITEMS"
export const FETCHBUYERORDERS ="FETCH_BUYER_ORDERS"

